CREATE DATABASE IF NOT EXISTS cinema;
use cinema;

CREATE TABLE IF NOT EXISTS users(
id INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
name VARCHAR(20) NOT NULL,
email VARCHAR(30) UNIQUE NOT NULL,
password VARCHAR(70) NOT NULL,
role VARCHAR(5) NOT NULL
);

CREATE TABLE IF NOT EXISTS movies(
id INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
title VARCHAR(20) NOT NULL,
description VARCHAR(300) NOT NULL,
image VARCHAR(150) NOT NULL
);

CREATE TABLE IF NOT EXISTS fav_movies(
id_user INT NOT NULL,
id_movie INT NOT NULL,
PRIMARY KEY (id_user, id_movie),
FOREIGN KEY (id_user) REFERENCES users (id),
FOREIGN KEY (id_movie) REFERENCES movies (id)
);


SELECT * FROM fav_movies;
SELECT * FROM users;
SELECT * FROM movies;


